CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'okavak'@'%' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON wordpress.* TO 'okavak'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '123';
